---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
      - recipe[workstation::tmux]
      - recipe[workstation::dotfiles]
      - recipe[workstation::vim]
      - recipe[ruby::rbenv]
      - recipe[ruby::ruby-build]
      - recipe[ruby]
    attributes:
